FROM node:alpine

# Set working directory
WORKDIR /forentend

# Copy package.json first for layer caching
COPY package.json ./

# Clear npm cache
RUN npm cache clean --force

# Delete package-lock.json (optional, only if needed)
RUN rm -f package-lock.json

# Install dependencies
RUN npm install

# Copy the rest of the files
COPY ./ ./

# Default command
CMD ["npm","run","start"]

